language: objective-c
osx_image: xcode9

script:
  - xcodebuild test -project Example/EZKeychain.xcworkspace -scheme EZKeychain_Example -destination "platform=iOS Simulator,name=iPhone 8" -sdk iphonesimulator11.0 CODE_SIGNING_REQUIRED=NO
