language: objective-c
osx_image: xcode9
podfile: Example/Podfile

script:
  - xcodebuild test -workspace Example/EZKeychain.xcworkspace -scheme EZKeychain-Example -destination "platform=iOS Simulator,name=iPhone 8" -sdk iphonesimulator11.0
